/*
  Edge function to generate E-FIR PDF documents
  Input: { alert_id }
  Output: { pdf_url }
*/

import { createClient } from 'npm:@supabase/supabase-js@2'

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
}

interface EFIRRequest {
  alert_id: string
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    })
  }

  try {
    const { alert_id }: EFIRRequest = await req.json()

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Fetch alert details
    const { data: alert, error: alertError } = await supabase
      .from('alerts')
      .select(`
        *,
        trips (
          *,
          profiles (
            full_name
          )
        )
      `)
      .eq('id', alert_id)
      .single()

    if (alertError || !alert) {
      throw new Error('Alert not found')
    }

    // Generate simple PDF content (in a real app, use a proper PDF library)
    const pdfContent = generatePDFContent(alert)
    
    // Save to storage (mock - in real app, generate actual PDF bytes)
    const fileName = `efir-${alert_id}-${Date.now()}.pdf`
    
    // For demo, return a mock URL
    const mockPdfUrl = `${Deno.env.get('SUPABASE_URL')}/storage/v1/object/public/efirs/${fileName}`

    return new Response(
      JSON.stringify({ pdf_url: mockPdfUrl }),
      {
        headers: {
          'Content-Type': 'application/json',
          ...corsHeaders,
        },
      },
    )
  } catch (error) {
    console.error('Error generating E-FIR:', error)
    return new Response(
      JSON.stringify({ error: 'Failed to generate E-FIR PDF' }),
      {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
          ...corsHeaders,
        },
      },
    )
  }
})

function generatePDFContent(alert: any): string {
  return `
    E-FIR DOCUMENT
    ==============
    
    FIR No: ${alert.id}
    Date: ${new Date(alert.created_at).toLocaleDateString()}
    Time: ${new Date(alert.created_at).toLocaleTimeString()}
    
    INCIDENT DETAILS:
    Type: ${alert.type}
    Status: ${alert.status}
    
    TOURIST DETAILS:
    Name: ${alert.trips?.profiles?.full_name || 'Unknown'}
    Trip ID: ${alert.trip_id}
    
    LOCATION:
    ${JSON.stringify(alert.details?.location || 'Unknown')}
    
    ADDITIONAL DETAILS:
    ${JSON.stringify(alert.details || {})}
    
    Generated by Saarthi Suraksha System
    Digital signature: ${alert.id.substring(0, 16)}...
  `
}